### ISSUE TITLE
404 Not Found when running knife node list

### ISSUE THREAD

**Issue by jmiddleton** [c-buisson/chef-server#2]
I have running your chef-server and another docker images with knife acting as a workstation. When I try to list the node, I'm getting 404 Not Found. I have followed the below tutorial to set my workstation and everything looks configured, however I'm not sure why I'm getting 404. 

My workstation configuration is:

root@ec33ddcd4e34:~/chef-repo# chef -v  
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-chef-12-configuration-management-system-on-ubuntu-14-04-servers

Can you give me a hint where I can start checking the config?

Thanks,
Jorge

**Comment by c-buisson** [comment]
Hello @jmiddleton,

Hmm, it could happen due to couple things.
-Are you sure the container is running? 
-Have you look at the install log: ```~/install-chef-out/out.txt``` ? Maybe the install failed?!

Just in case, here is the content of my ```knife.rb```:
```
log_level                :info
log_location             STDOUT
cache_type               'BasicFile'
node_name                'admin'
client_key               '/home/cbuisson/.chef/admin.pem'
validation_client_name   'chef-validator'
validation_key           '/home/cbuisson/.chef/chef-validator.pem'
chef_server_url          'https://192.168.1.10:4443'
```
You could also take a look at ```netstat``` and check if the port was correctly assigned.

Let me know!

**Comment by justmiles** [comment]
I ran into this issue as well. `knife ssl check

**Comment by c-buisson** [comment]
Closing this.
