### ISSUE TITLE
Hostname Mismatch with SSL Cert

### ISSUE THREAD

**Issue by tstirrat15** [c-buisson/chef-server#3]
I'm trying to work my way through the Chef tutorials, using this docker image as a self-hosted server.

I ran the server using:
`docker run --privileged -e CHEF_PORT=443 --name chef-server -d -v ~/chef-logs:/var/log -v ~/install-chef-out:/root -p 443:443 cbuisson/chef-server`

and then fetched the SSL certs using:
`knife ssl fetch`
in my working directory on the same machine.

I then ran:
`knife ssl check`
per the instructions on the Chef site, which produced this error:

``` bash
Connecting to host localhost:443
ERROR: The SSL cert is signed by a trusted authority but is not valid for the given hostname
ERROR: You are attempting to connect to:   'localhost'
ERROR: The server's certificate belongs to 'ebb63c73161d'

TO FIX THIS ERROR:

The solution for this issue depends on your networking configuration. If you
are able to connect to this server using the hostname ebb63c73161d
instead of localhost, then you can resolve this issue by updating chef_server_url
in your configuration file.

If you are not able to connect to the server using the hostname ebb63c73161d
you will have to update the certificate on the server to use the correct hostname.
```

It looks like the ssl certs are being generated using the docker-internal hostname. Is this a known issue? How do I get around it?

**Comment by ddaymn** [comment]
knife ssl fetch

**Comment by c-buisson** [comment]
@tstirrat15, the latest commit will supports Chef Server 12.
`knife ssl fetch` and `knife ssl check` should work as long as the container_id is resolvable on your server.
Please take a look at the README file and let me know if you need more help!
