### ISSUE TITLE
Unable to install chef-manage

### ISSUE THREAD

**Issue by SergiuCip** [c-buisson/chef-server#5]
Hi,

Thank you for this great Docker container. 

I am trying to bring up the WebUI on this container however, when I try to install chef-manage I get this error:

` * apt_package[chef-manage] action install

    ================================================================================
    Error executing action `install` on resource 'apt_package[chef-manage]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
    STDOUT: Selecting previously unselected package chef-manage.
    (Reading database ... 75837 files and directories currently installed.)
    Preparing to unpack .../chef-manage_2.5.4-1_amd64.deb ...
    Unpacking chef-manage (2.5.4-1) ...
    STDERR: dpkg: dependency problems prevent configuration of chef-manage:
     chef-manage depends on chef-server-core (>= 12.14.0); however:
      Version of chef-server-core on system is 12.13.0-1.

    dpkg: error processing package chef-manage (--install):
     dependency problems - leaving unconfigured
    Errors were encountered while processing:
     chef-manage
    ---- End output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
    Ran dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb returned 1

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb

     88:   package pkg do
     89:     provider value_for_platform_family(
     90:       ['debian']       => Chef::Provider::Package::Dpkg,
     91:       ['rhel', 'suse'] => Chef::Provider::Package::Rpm,
     92:     )
     93:     source lazy { pkg_file }
     94:     notifies :create, "ruby_block[addon_install_notification_#{pkg}]", :immediate
     95:   end
     96: end

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:88:in `block in from_file'

    apt_package("chef-manage") do
      package_name "chef-manage"
      provider Chef::Provider::Package::Dpkg
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "private-chef"
      recipe_name "add_ons_wrapper"
      source #<Chef::DelayedEvaluator:0x0000000740d948@/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:93>
    end

    Platform:
    ---------
    x86_64-linux

Running handlers:
  - #<Class:0x00000005e25428>::AddonInstallHandler
Running handlers complete
Chef Client failed. 1 resources updated in 17 seconds
[2017-08-22T09:44:40+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2017-08-22T09:44:40+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-22T09:44:40+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: apt_package[chef-manage] (private-chef::add_ons_wrapper line 88) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
STDOUT: Selecting previously unselected package chef-manage.
(Reading database ... 75837 files and directories currently installed.)
Preparing to unpack .../chef-manage_2.5.4-1_amd64.deb ...
Unpacking chef-manage (2.5.4-1) ...
STDERR: dpkg: dependency problems prevent configuration of chef-manage:
 chef-manage depends on chef-server-core (>= 12.14.0); however:
  Version of chef-server-core on system is 12.13.0-1.

dpkg: error processing package chef-manage (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 chef-manage
---- End output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
Ran dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb returned 1`

Do you know what the problem / solution might be?

Thanks

**Comment by c-buisson** [comment]
Hello @SergiuCip,

The WebUI isn't available in a container (As mentioned in the Readme).
Chef-Server in a container isn't officially supported by Chef. It does work but features like the WebUI aren't available. I talked to [coderanger](https://github.com/coderanger) over IRC back in March 2017 who confirmed that to me.

That said, you should be able to achieve what you need by using the `knife` command.

Thanks,
Clement

**Comment by SergiuCip** [comment]
@c-buisson Thanks a lot for the explanation. I do apologise for creating this ticket and yes I was aware about not "officially supporting it", however, I was thinking I might be able to install chef-manage, however, it is using the package that is already in the repo and fails to install.

Thanks,
Sergiu

**Comment by c-buisson** [comment]
Hello @SergiuCip,

Chef-manage can be installed now. Thanks for reporting this issue!
Let me know if it works for you.

Clement

**Comment by SergiuCip** [comment]
Hello @c-buisson ,

That unfortunately, that didn't do it

`STDERR: dpkg: dependency problems prevent configuration of chef-manage:
 chef-manage depends on chef-server-core (>= 12.14.0); however:
  Version of chef-server-core on system is 12.13.0-1.

dpkg: error processing package chef-manage (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 chef-manage
---- End output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
Ran dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb returned 1

Resource Declaration:
---------------------
# In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb

 88:   package pkg do
 89:     provider value_for_platform_family(
 90:       ['debian']       => Chef::Provider::Package::Dpkg,
 91:       ['rhel', 'suse'] => Chef::Provider::Package::Rpm,
 92:     )
 93:     source lazy { pkg_file }
 94:     notifies :create, "ruby_block[addon_install_notification_#{pkg}]", :immediate
 95:   end
 96: end

Compiled Resource:
------------------
# Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:88:in `block in from_file'

apt_package("chef-manage") do
  package_name "chef-manage"
  provider Chef::Provider::Package::Dpkg
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :package
  cookbook_name "private-chef"
  recipe_name "add_ons_wrapper"
  source #<Chef::DelayedEvaluator:0x00000006153848@/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:93>
end

Platform:
---------
x86_64-linux

[2017-08-25T11:24:58+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2017-08-25T11:24:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-25T11:24:58+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: apt_package[chef-manage] (private-chef::add_ons_wrapper line 88) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
STDOUT: Selecting previously unselected package chef-manage.
(Reading database ... 75837 files and directories currently installed.)
Preparing to unpack .../chef-manage_2.5.4-1_amd64.deb ...
Unpacking chef-manage (2.5.4-1) ...
STDERR: dpkg: dependency problems prevent configuration of chef-manage:
 chef-manage depends on chef-server-core (>= 12.14.0); however:
  Version of chef-server-core on system is 12.13.0-1.

dpkg: error processing package chef-manage (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 chef-manage
---- End output of dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb ----
Ran dpkg -i /var/opt/opscode/local-mode-cache/chef-manage_2.5.4-1_amd64.deb returned 1
+ tee -a /root/out.txt
+ echo -e '\nRunning: chef-server-ctl reconfigure'
`

However, I have created a pull request using the latest version of chef-server. I have used this locally from when this issue occurred and works well.

Thanks,
Sergiu

**Comment by c-buisson** [comment]
Hello @SergiuCip,

I never ran into that issue until I tried to run the container on my MacBook. Thanks for reporting it!
I disabled IPv6 support in `run.sh` to mitigate that possible issue.

Let me know if you can run the image without issue now.
Thank you again.

**Comment by SergiuCip** [comment]
👍
